# Copyright 2022 TriggerMesh Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# All sources used at TriggerMesh

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: triggermesh-sources-admin
  labels:
    rbac.triggermesh.io/sources-admin: "true"
rules:
- apiGroups:
  - sources.knative.dev
  - sources.eventing.knative.dev
  - sources.eventing.triggermesh.dev
  - sources.triggermesh.io
  resources: ["*"]
  verbs:
  - get
  - list
  - create
  - update
  - patch
  - delete
  - deletecollection
  - watch

---

# All targets used at TriggerMesh

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: triggermesh-targets-admin
  labels:
    rbac.triggermesh.io/targets-admin: "true"
rules:
- apiGroups:
  - targets.triggermesh.io
  resources: ["*"]
  verbs:
  - get
  - list
  - create
  - update
  - patch
  - delete
  - watch

---

# All Kantive eventing objects used at TriggerMesh

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: triggermesh-knative-admin
  labels:
    rbac.triggermesh.io/knative-admin: "true"
rules:
- apiGroups:
  - serving.knative.dev
  - eventing.knative.dev
  - messaging.knative.dev
  - messaging.triggermesh.dev
  resources:
  - brokers
  - channels
  - configurations
  - revisions
  - routes
  - triggers
  - subscriptions
  - services
  - kinesischannels
  - inmemorychannels
  - clusterchannelprovisioners
  verbs:
  - get
  - list
  - create
  - update
  - patch
  - delete
  - deletecollection
  - watch

---

# Kubernetes objects for TriggerMesh users
# NOTE: dupe at config repo, label changed to
#       match other labels pattern at ClusterRoles.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: triggermesh-kubernetes-admin
  labels:
    rbac.triggermesh.io/kubernetes-admin: "true"
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  - pods/exec
  - services
  - serviceaccounts
  - secrets
  - configmaps
  verbs:
  - get
  - list
  - create
  - update
  - patch
  - delete
  - deletecollection
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - create
  - update
  - patch
  - delete
  - deletecollection
  - watch

---

# TriggerMesh bridges object
# NOTE: dupe at config repo, label name
#       changed to match other labels pattern.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: triggermesh-flow-admin
  labels:
    rbac.triggermesh.io/flow-admin: "true"
rules:
- apiGroups:
  - flow.triggermesh.io
  resources: ["*"]
  verbs:
  - get
  - list
  - create
  - update
  - patch
  - delete
  - watch

